version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - backend
    expose:
      - 5000
    environment:
      POSTGRES_URL: postgres://root:JUIHKJAHSD87676@hackqc2019.ceixem2ut2a6.us-east-2.rds.amazonaws.com/postgres?sslrootcert=/server/config/rds-combined-ca-bundle.cer
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: JUIHKJAHSD87676
      POSTGRES_HOST: hackqc2019.ceixem2ut2a6.us-east-2.rds.amazonaws.com
  
  postgres:
    image: postgres
    environment:         
      POSTGRES_DB: hackqc19
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgres/
    volumes: 
      - postgres:/var/lib/postgres/
    networks:
      - backend
    ports:
      - "5432:5432"
    expose:
      - 5432
    

networks:
  backend:

volumes:
  postgres: